<?php

namespace ContainerFMgJeBH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PKdMXitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PKdMXit' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PKdMXit'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transport' => ['privates', '.errored..service_locator.PKdMXit.App\\Entity\\Transport', NULL, 'Cannot autowire service ".service_locator.PKdMXit": it references class "App\\Entity\\Transport" but no such service exists.'],
        ], [
            'transport' => 'App\\Entity\\Transport',
        ]);
    }
}
