<?php

namespace ContainerFvwHzff;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Y9aiQT9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Y9aiQT9' shared service.
     *
     * @return \App\Controller\Colis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\SerializerController::delete()": the $colis argument is type-hinted with the non-existent class or interface: "App\\Controller\\Colis". Did you forget to add a use statement?');
    }
}
