<?php

namespace ContainerUuXo7su;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AvSuyADService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.avSuyAD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.avSuyAD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
            'req' => ['privates', '.errored.q_764an', NULL, 'Cannot determine controller argument for "App\\Controller\\SerializerController::updateJson()": the $req argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'Normalizer' => '?',
            'req' => '?',
        ]);
    }
}
