<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/get_ServiceLocator_IGUm1r8Service.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/get_ServiceLocator_ZJzZ1Z2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZJzZ1Z2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZJzZ1Z2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZJzZ1Z2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produit' => ['privates', '.errored..service_locator.ZJzZ1Z2.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.ZJzZ1Z2": it references class "App\\Entity\\Produit" but no such service exists.'],
        ], [
            'produit' => 'App\\Entity\\Produit',
        ]);
    }
}
