<?php

<<<<<<<< HEAD:var/cache/dev/Container1kiG494/get_ServiceLocator_VhSGKsAService.php
namespace Container1kiG494;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/get_ServiceLocator_3LMAeMService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3LMAeMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3LMAe_M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3LMAe_M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'abonnement' => ['privates', '.errored..service_locator.3LMAe_M.App\\Entity\\Abonnement', NULL, 'Cannot autowire service ".service_locator.3LMAe_M": it references class "App\\Entity\\Abonnement" but no such service exists.'],
            'abonnementRepository' => ['privates', 'App\\Repository\\AbonnementRepository', 'getAbonnementRepositoryService', true],
        ], [
            'abonnement' => 'App\\Entity\\Abonnement',
            'abonnementRepository' => 'App\\Repository\\AbonnementRepository',
        ]);
    }
}
