<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/get_ServiceLocator_YAvMNdPService.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/get_ServiceLocator_M32XZm7Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M32XZm7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m32XZm7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m32XZm7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.m32XZm7.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.m32XZm7": it references class "App\\Entity\\Evenement" but no such service exists.'],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
        ]);
    }
}
