<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/getAbonnementService.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/getAbonnementService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3LMAe_M.App\Entity\Abonnement' shared service.
     *
     * @return \App\Entity\Abonnement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3LMAe_M": it references class "App\\Entity\\Abonnement" but no such service exists.');
    }
}
