<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/getCategorieProdService.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/getCategorieProdService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieProdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XB8m1aF.App\Entity\CategorieProd' shared service.
     *
     * @return \App\Entity\CategorieProd
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XB8m1aF": it references class "App\\Entity\\CategorieProd" but no such service exists.');
    }
}
