<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/getEvenementService.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/getEvenementService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1nvu1je.App\Entity\Evenement' shared service.
     *
     * @return \App\Entity\Evenement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1nvu1je": it references class "App\\Entity\\Evenement" but no such service exists.');
    }
}
