<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/getReclamations2Service.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/getReclamations2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamations2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Dq79EF6.App\Entity\Reclamations' shared service.
     *
     * @return \App\Entity\Reclamations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Dq79EF6": it references class "App\\Entity\\Reclamations" but no such service exists.');
    }
}
