<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/getReservation22Service.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/getReservation22Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S5ausl9.App\Entity\Reservation2' shared service.
     *
     * @return \App\Entity\Reservation2
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S5ausl9": it references class "App\\Entity\\Reservation2" but no such service exists.');
    }
}
