<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/getTransport2Service.php
namespace Container4epoOLh;
========
namespace ContainerXVF9GhU;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerXVF9GhU/getTransport2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HufE5Aw.App\Entity\Transport' shared service.
     *
     * @return \App\Entity\Transport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HufE5Aw": it references class "App\\Entity\\Transport" but no such service exists.');
    }
}
