<?php

namespace ContainerYyV6xRA;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GXmRZDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GXmR_ZD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GXmR_ZD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'reservation' => ['privates', '.errored..service_locator.GXmR_ZD.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.GXmR_ZD": it references class "App\\Entity\\Reservation" but no such service exists.'],
        ], [
            'repository' => 'App\\Repository\\ReservationRepository',
            'reservation' => 'App\\Entity\\Reservation',
        ]);
    }
}
