#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

app_login:
  path: /login
  controller: App\Controller\SecurityController::login


app_users_list:
  path: /users
  controller: App\Controller\UsersController::index
