<?php

<<<<<<<< HEAD:var/cache/dev/Container6GyGKWz/getReservation3Service.php
namespace Container6GyGKWz;
========
namespace ContainerWExVuzY;

>>>>>>>> RymBranch:var/cache/dev/ContainerWExVuzY/getReservation3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jtI7Unb.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jtI7Unb": it references class "App\\Entity\\Reservation" but no such service exists.');
    }
}
