<?php

<<<<<<<< HEAD:var/cache/dev/Container6GyGKWz/getUsers2Service.php
<<<<<<<< HEAD:var/cache/dev/ContainerQv7k3lb/getUsers2Service.php
namespace ContainerQv7k3lb;

========
namespace Container6GyGKWz;
>>>>>>>> MalekBranch:var/cache/dev/Container6GyGKWz/getUsers2Service.php
========
namespace ContainerWExVuzY;

>>>>>>>> RymBranch:var/cache/dev/ContainerWExVuzY/getUsers2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsers2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cyg1ViB.App\Entity\Users' shared service.
     *
     * @return \App\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cyg1ViB": it references class "App\\Entity\\Users" but no such service exists.');
    }
}
