<?php

namespace ContainerZP5CK9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TwUyKIxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.twUyKIx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.twUyKIx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colis' => ['privates', '.errored.Y9aiQT9', NULL, 'Cannot determine controller argument for "App\\Controller\\SerializerController::delete()": the $colis argument is type-hinted with the non-existent class or interface: "App\\Controller\\Colis". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.5kHlvWV', NULL, 'Cannot determine controller argument for "App\\Controller\\SerializerController::delete()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'colis' => '?',
            'request' => '?',
        ]);
    }
}
