<?php

<<<<<<<< HEAD:var/cache/dev/ContainerQv7k3lb/getProduit2Service.php
namespace ContainerQv7k3lb;

========
namespace Container6GyGKWz;
>>>>>>>> MalekBranch:var/cache/dev/Container6GyGKWz/getProduit2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduit2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iGUm1r8.App\Entity\Produit' shared service.
     *
     * @return \App\Entity\Produit
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iGUm1r8": it references class "App\\Entity\\Produit" but no such service exists.');
    }
}
