<?php

namespace ContainerQWBLtCu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PKdMXit.App\Entity\Transport' shared service.
     *
     * @return \App\Entity\Transport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PKdMXit": it references class "App\\Entity\\Transport" but no such service exists.');
    }
}
