<?php

<<<<<<<< HEAD:var/cache/dev/ContainerQv7k3lb/get_ServiceLocator_JtI7UnbService.php
namespace ContainerQv7k3lb;

========
namespace Container3eXcBqx;
>>>>>>>> MalekBranch:var/cache/dev/Container3eXcBqx/get_ServiceLocator_JtI7UnbService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JtI7UnbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jtI7Unb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jtI7Unb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservation' => ['privates', '.errored..service_locator.jtI7Unb.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.jtI7Unb": it references class "App\\Entity\\Reservation" but no such service exists.'],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
        ]);
    }
}
