<?php

namespace Container3eXcBqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1IVjUntService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1IVjUnt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1IVjUnt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
            'user' => ['privates', '.errored..service_locator.1IVjUnt.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.1IVjUnt": it references class "App\\Entity\\Users" but no such service exists.'],
        ], [
            'normalizer' => '?',
            'user' => 'App\\Entity\\Users',
        ]);
    }
}
