<?php

namespace Container3eXcBqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieEvent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T_GcY.G.App\Entity\CategorieEvent' shared service.
     *
     * @return \App\Entity\CategorieEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.T_GcY.G": it references class "App\\Entity\\CategorieEvent" but no such service exists.');
    }
}
