<?php

<<<<<<<< HEAD:var/cache/dev/ContainerQv7k3lb/getEvenementService.php
namespace ContainerQv7k3lb;

========
namespace Container3eXcBqx;
>>>>>>>> MalekBranch:var/cache/dev/Container3eXcBqx/getEvenementService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wXSRjZL.App\Entity\Evenement' shared service.
     *
     * @return \App\Entity\Evenement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wXSRjZL": it references class "App\\Entity\\Evenement" but no such service exists.');
    }
}
