<?php

<<<<<<<< HEAD:var/cache/dev/ContainerQv7k3lb/getReservation2Service.php
namespace ContainerQv7k3lb;

========
namespace Container3eXcBqx;
>>>>>>>> MalekBranch:var/cache/dev/Container3eXcBqx/getReservation2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gZIaKpL.App\Entity\Reservation2' shared service.
     *
     * @return \App\Entity\Reservation2
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gZIaKpL": it references class "App\\Entity\\Reservation2" but no such service exists.');
    }
}
