<?php

namespace Container3eXcBqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1IVjUnt.App\Entity\Users' shared service.
     *
     * @return \App\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1IVjUnt": it references class "App\\Entity\\Users" but no such service exists.');
    }
}
