<?php

namespace ContainerMNxpgRO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3ax0K2OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3ax0K2O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3ax0K2O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', '.errored.CjR8Pbh', NULL, 'Cannot determine controller argument for "App\\Controller\\UsersController::edit()": the $passwordHasher argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordHasherInterface".'],
            'user' => ['privates', '.errored..service_locator.3ax0K2O.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.3ax0K2O": it references class "App\\Entity\\Users" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'user' => 'App\\Entity\\Users',
        ]);
    }
}
