<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerZEEs7nx/getCategorieProdService.php
namespace ContainerZEEs7nx;
========
namespace Container6P8OaWR;
>>>>>>>> Stashed changes:var/cache/dev/Container6P8OaWR/getCategorieProdService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieProdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VQlfM9F.App\Entity\CategorieProd' shared service.
     *
     * @return \App\Entity\CategorieProd
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VQlfM9F": it references class "App\\Entity\\CategorieProd" but no such service exists.');
    }
}
