<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerZEEs7nx/getEvenementService.php
namespace ContainerZEEs7nx;
========
namespace Container6P8OaWR;
>>>>>>>> Stashed changes:var/cache/dev/Container6P8OaWR/getEvenementService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wXSRjZL.App\Entity\Evenement' shared service.
     *
     * @return \App\Entity\Evenement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wXSRjZL": it references class "App\\Entity\\Evenement" but no such service exists.');
    }
}
