<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerZEEs7nx/getEvenement2Service.php
namespace ContainerZEEs7nx;
========
namespace Container6P8OaWR;
>>>>>>>> Stashed changes:var/cache/dev/Container6P8OaWR/getEvenement2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yAvMNdP.App\Entity\Evenement' shared service.
     *
     * @return \App\Entity\Evenement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yAvMNdP": it references class "App\\Entity\\Evenement" but no such service exists.');
    }
}
