<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerZEEs7nx/getProduitService.php
namespace ContainerZEEs7nx;
========
namespace Container6P8OaWR;
>>>>>>>> Stashed changes:var/cache/dev/Container6P8OaWR/getProduitService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HkHf8J3.App\Entity\Produit' shared service.
     *
     * @return \App\Entity\Produit
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HkHf8J3": it references class "App\\Entity\\Produit" but no such service exists.');
    }
}
