<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerZEEs7nx/getReservation3Service.php
namespace ContainerZEEs7nx;
========
namespace Container6P8OaWR;
>>>>>>>> Stashed changes:var/cache/dev/Container6P8OaWR/getReservation3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kcphr5g.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kcphr5g": it references class "App\\Entity\\Reservation" but no such service exists.');
    }
}
