<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerZEEs7nx/getUsers3Service.php
namespace ContainerZEEs7nx;
========
namespace Container6P8OaWR;
>>>>>>>> Stashed changes:var/cache/dev/Container6P8OaWR/getUsers3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsers3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yRRNQrI.App\Entity\Users' shared service.
     *
     * @return \App\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yRRNQrI": it references class "App\\Entity\\Users" but no such service exists.');
    }
}
