<?php

namespace Container9OcH4hl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MHm6mei.App\Entity\Reclamations' shared service.
     *
     * @return \App\Entity\Reclamations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MHm6mei": it references class "App\\Entity\\Reclamations" but no such service exists.');
    }
}
