<?php

<<<<<<<< Updated upstream:var/cache/dev/Container00UJSnM/get_ServiceLocator_IZvucfQService.php
namespace Container00UJSnM;
========
namespace ContainerMnVKAAF;
>>>>>>>> Stashed changes:var/cache/dev/ContainerMnVKAAF/get_ServiceLocator_IZvucfQService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IZvucfQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iZvucfQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iZvucfQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\AbonnementRepository', 'getAbonnementRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\AbonnementRepository',
        ]);
    }
}
