<?php

<<<<<<<< Updated upstream:var/cache/dev/Container00UJSnM/getReservation22Service.php
namespace Container00UJSnM;
========
namespace ContainerMnVKAAF;
>>>>>>>> Stashed changes:var/cache/dev/ContainerMnVKAAF/getReservation22Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.y.Ows6z.App\Entity\Reservation2' shared service.
     *
     * @return \App\Entity\Reservation2
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.y.Ows6z": it references class "App\\Entity\\Reservation2" but no such service exists.');
    }
}
