<?php

<<<<<<<< Updated upstream:var/cache/dev/Container00UJSnM/getReclamations2Service.php
namespace Container00UJSnM;
========
namespace ContainerMnVKAAF;
>>>>>>>> Stashed changes:var/cache/dev/ContainerMnVKAAF/getReclamations2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamations2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oEfCGgo.App\Entity\Reclamations' shared service.
     *
     * @return \App\Entity\Reclamations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oEfCGgo": it references class "App\\Entity\\Reclamations" but no such service exists.');
    }
}
