<?php

namespace ContainerIkpymFn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JZKfgDOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.JZKfgDO' shared service.
     *
     * @return \Gregwar\CaptchaBundle\CaptchaBuilderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $captchaBuilder argument is type-hinted with the non-existent class or interface: "Gregwar\\CaptchaBundle\\CaptchaBuilderInterface".');
    }
}
