<?php

namespace ContainerB6UOwIP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KhrFsUJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.khrFsUJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.khrFsUJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'FactureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'FactureRepository' => 'App\\Repository\\FactureRepository',
            'paginator' => '?',
        ]);
    }
}
