<?php

<<<<<<<< HEAD:var/cache/dev/Container4epoOLh/get_ServiceLocator_OifERqRService.php
namespace Container4epoOLh;
========
namespace ContainerB6UOwIP;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerB6UOwIP/get_ServiceLocator_BEMpSSkService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BEMpSSkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bEMpSSk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bEMpSSk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ReservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repoEvent' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'ReservationRepository' => 'App\\Repository\\ReservationRepository',
            'paginator' => '?',
            'repoEvent' => 'App\\Repository\\EventRepository',
        ]);
    }
}
