<?php

namespace ContainerB6UOwIP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieProd2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rh_SeH1.App\Entity\CategorieProd' shared service.
     *
     * @return \App\Entity\CategorieProd
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rh_SeH1": it references class "App\\Entity\\CategorieProd" but no such service exists.');
    }
}
