<?php

<<<<<<<< HEAD:var/cache/dev/Container1kiG494/getReclamationsService.php
namespace Container1kiG494;
========
namespace ContainerB6UOwIP;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerB6UOwIP/getReclamationsService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4cxrjS6.App\Entity\Reclamations' shared service.
     *
     * @return \App\Entity\Reclamations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.4cxrjS6": it references class "App\\Entity\\Reclamations" but no such service exists.');
    }
}
