<?php

<<<<<<<< HEAD:var/cache/dev/Container1kiG494/getReservation3Service.php
namespace Container1kiG494;
========
namespace ContainerB6UOwIP;
>>>>>>>> 9ea38196d607f303b1d99017947157b148f6168e:var/cache/dev/ContainerB6UOwIP/getReservation3Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T8q8jja.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.T8q8jja": it references class "App\\Entity\\Reservation" but no such service exists.');
    }
}
