<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\Container00UJSnM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container00UJSnM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container00UJSnM.legacy');
=======
if (\class_exists(\ContainerMnVKAAF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnVKAAF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMnVKAAF.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\Container00UJSnM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container00UJSnM\App_KernelDevDebugContainer([
    'container.build_hash' => '00UJSnM',
    'container.build_id' => 'b04cdf14',
    'container.build_time' => 1683241023,
], __DIR__.\DIRECTORY_SEPARATOR.'Container00UJSnM');
=======
    \class_alias(\ContainerMnVKAAF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMnVKAAF\App_KernelDevDebugContainer([
    'container.build_hash' => 'MnVKAAF',
    'container.build_id' => '5ee0269a',
    'container.build_time' => 1683234400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnVKAAF');
>>>>>>> Stashed changes
