<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerZhZxGFQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhZxGFQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZhZxGFQ.legacy');
=======
if (\class_exists(\ContainerQ08mIBs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ08mIBs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ08mIBs.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerZhZxGFQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZhZxGFQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZhZxGFQ',
    'container.build_id' => '84ab9a04',
    'container.build_time' => 1683211481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhZxGFQ');
=======
    \class_alias(\ContainerQ08mIBs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ08mIBs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q08mIBs',
    'container.build_id' => '33b095c3',
    'container.build_time' => 1683209233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ08mIBs');
>>>>>>> Stashed changes
