<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExjKz3n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExjKz3n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExjKz3n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExjKz3n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExjKz3n\App_KernelDevDebugContainer([
    'container.build_hash' => 'ExjKz3n',
    'container.build_id' => '9fcbfbf4',
    'container.build_time' => 1682637730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExjKz3n');
