<?php

namespace ContainerZhZxGFQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGw4C5SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PGw4C5S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PGw4C5S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieEvent' => ['privates', '.errored..service_locator.PGw4C5S.App\\Entity\\CategorieEvent', NULL, 'Cannot autowire service ".service_locator.PGw4C5S": it references class "App\\Entity\\CategorieEvent" but no such service exists.'],
        ], [
            'categorieEvent' => 'App\\Entity\\CategorieEvent',
        ]);
    }
}
