<?php

<<<<<<<< HEAD:var/cache/dev/ContainerUuXo7su/getFactureService.php
namespace ContainerUuXo7su;
========
namespace ContainerFz25pDv;

>>>>>>>> RymBranch:var/cache/dev/ContainerFz25pDv/getFactureService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFactureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XVjfyza.App\Entity\Facture' shared service.
     *
     * @return \App\Entity\Facture
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XVjfyza": it references class "App\\Entity\\Facture" but no such service exists.');
    }
}
