<?php

<<<<<<<< HEAD:var/cache/dev/ContainerUuXo7su/getUsers2Service.php
namespace ContainerUuXo7su;
========
namespace ContainerFz25pDv;

>>>>>>>> RymBranch:var/cache/dev/ContainerFz25pDv/getUsers2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsers2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cyg1ViB.App\Entity\Users' shared service.
     *
     * @return \App\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cyg1ViB": it references class "App\\Entity\\Users" but no such service exists.');
    }
}
